### ISSUE TITLE
How to Understand the Numerous ply Files Output by the Model（scannet datanet）

### ISSUE THREAD

**Issue by justbin1123** [yangyanli/PointCNN#143]
I got the numerous ply data when  i ran scannet dataset on pointCNN.I thought every file represented a separate object in the whole scene，but its not. I found that every ply file is just a tiny part of the whole scene. How to Understand those Numerous ply Files？ OR how can i get each part that be partitioned？

**Comment by MingChaoSun** [comment]
Hi @justbin1123 

For large scene datasets like ScanNet， due to the limited number of input points， We split the scene into many blocks and segmentation on each block, finally, merge blocks to whole scene.

If you want visualize the result of the whole scene, I think [issues#104]https://github.com/yangyanli/PointCNN/issues/104) may help you～

Thanks

**Comment by justbin1123** [comment]
@MingChaoSun Thank you so much,ill try!
