### ISSUE TITLE
Visualization of X-Conv features

### ISSUE THREAD

**Issue by thinker111** [yangyanli/PointCNN#156]
Hi,
Your work is so exciting that I spent some days reading your codes.
When I want to use T-SNE  for the visualization of X-conv features,just as what you wrote in the paper——'Visualization of X-Conv features'，but I could not find your codes regarding to this.
Did you implement such visualization via tensorboard's  projector or other ways,could you please give me some hints?
Looking forward to your answer!

**Comment by thinker111** [comment]
when i count the color in your Figure 5，i found there are 16 colors in it,but your paper says that you visualize of F0,F*,Fx of 15 randomly picked representative points from the Modelnet40, so  i confused what is 15 meaning.Could you please upload the codes of visualiaztion to make me understand  the entire process better?
![image](https://user-images.githubusercontent.com/43626857/55929212-33562980-5c4e-11e9-9b37-3585bcdd65e2.png)
Looking forward to your answer!

**Comment by burui11087** [comment]
Hi @thinker111 

The T-SNE is implemented by scikit-learn, I can upload visualization code but maby it's still hard to use because  the way to get features from network is very complex, and the code will destory the structure of  our opensource code. If you are interested in visualization, you can contact me with email, I can send it to you.

For the second issue, a and b have 15 block indeed, and one of them is devided to two block.

Thanks!

**Comment by thinker111** [comment]
Hi @burui11087 
Thank you for your reply.  Your explaination of the second issue has solved my confusion.And I am sorry to bother you again that I have send emails to you few days ago since I am still interested in visualization.
Hope for you reply!
Thank you!

**Comment by burui11087** [comment]
Sorry, I haven’t received your email in my email, which address you sent. You can contact me with following email:527650378@qq.com

Best！

Rui
