### ISSUE TITLE
Can this be used to identify landmark? Or extract measurement?

### ISSUE THREAD

**Issue by vhanded** [yangyanli/PointCNN#166]
Thanks for this wonderful work. I had tried out your sample for classification and segmentation, and now I would like to perform landmarks extraction from human body point cloud, like identify shoulder point / waist level, and extract the distance between landmarks

How can this be done using segmentation? Or any better idea?

Thanks.

**Comment by yangyanli** [comment]
Hi @vhanded ，

I assume you have training data for the landmark identification task. In this case, there can be a straight forward way to enable the support of this task:
1. find some neighboring points around the landmarks;
2. compute the offset from each point to its associated landmark point;
3. train a network to predict the offsets.

This is pretty much like segmentation (per point prediction), the difference is that the network outputs the offset rather than the classification for each point. Of course, you can quantize the offsets into bins, and convert it into a classification problem... you may have to take care of the points that are on the "boundary" of being assigned to different landmarks.

We have tried similar approach for object detection, where the "landmarks" are the object centers (some "virtual" points), and it worked reasonably well.

**Comment by vhanded** [comment]
@yangyanli Thanks for your reply. I don't have the training data, plan to create about >50 for training. I had spent a lot of time everyday in my free time to read up regarding this, still troubled me.

And I am very new to Deep Learning, so new that this is practically my first project. So would really grateful if you bear with me with my silly questions.

Let's take a sphere /(Earth?) for example. Let's say I would like to train the network to output the distance of 2 landmarks, namely north pole and south pole, across the surface on earth. With your one-point segmentation, the network can easily pinpoint the north & south pole, which I think I can do it. But a better way that you suggest, is to get the neighboring points of the landmark, and train the network to predict the offset. How is the train data looks like exactly?

Second question, all your train data has points within 2500++ points, for my cloud with more than 100k per cloud, what suggestions for the RAM requirement for graphic cards?

Thanks.
