### ISSUE TITLE
Problem about training for quick draw and log

### ISSUE THREAD

**Issue by zxy14120448** [yangyanli/PointCNN#185]
When I run the ./train_val_quick_draw.sh -g 0 -x quick_draw_full_x2_l6, the log will stop when the data is loaded in 145. I do not what is the reason.

![WeChat Image_20190905195916](https://user-images.githubusercontent.com/20695624/64391673-aace9000-d017-11e9-9619-100828c1fd23.jpg)

My second question is that how to output the traning process to the log file and  terminal? The training process now is in the log only.

**Comment by burui11087** [comment]
Hi,
You can use 'htop' to check the resources usage such as memory, maybe it caused by OOM when loading 145 of 345.
For the second question, You can use `watch -n 1 tail -n 20 [path to log.txt]` to print log information immediately. But I recommend to use tensorboard to visualize training process. 
Thanks!

**Comment by zxy14120448** [comment]
Yes, thank you the answer. I find that the reason is my memory. Because the code will first load all the data in the CPU and the CPU in my computer is only 12G, which is hard to load all the dataset.

**Comment by zxy14120448** [comment]
Yes, thank you for the answer. I find that the reason is my memory. Because the code will first load all the data in the CPU and the CPU in my computer is only 12G, which is hard to load all the dataset.
