### ISSUE TITLE
question on the "links" usage 

### ISSUE THREAD

**Issue by amiltonwong** [yangyanli/PointCNN#33]
Hi, @yangyanli ,

According to these [lines](https://github.com/yangyanli/PointCNN/blob/master/pointcnn.py#L118-L125) in pointcnn.py, "links" are used there. Could you elaborate a bit on its function? Does it mean the connections/kernel_weights/feature_maps between two layers? 

THX!

**Comment by yangyanli** [comment]
The usage is briefly explained in the current homepage ReadMe. It is intended for building DenseNet style network with flexible feature forward links.

However, so far, we haven't observed significant improvement on the datasets we tried. We haven't test this idea on all of the datasets though.

**Comment by JDcodeing** [comment]
Hi, @yangyanli 

about the implementation of the feature forward links, I am a little confused about this line in the file pointcnn.py 
`fts_slice = tf.slice(fts_from_link, (0, 0, 0), (-1, P, -1), name=tag + 'fts_slice_' + str(-link))`
Shouldn't the features be selected according to the indices in order to guarantee the correspondences between the the seletecd points and the forwarded features? 

Please correct me if I am wrong. Thanks in advance!
