### ISSUE TITLE
train_val_shapenet.sh  shapenet_x8_2048_fps error

### ISSUE THREAD

**Issue by limin1130** [yangyanli/PointCNN#6]
Hi ,thanks for your share! 
when i  try to train the shapenet_x8_2048_fps,i accept a error which indicates that there is no "label_weights" in shapenet_x8_2048_fps.py. The code of train_val_seg.py does need the "label_weights" say `label_weights_list = setting.label_weights` .In your paper, it says 
> ShapeNet Parts contains 16, 880 models (14, 006/2, 874 training/ testing split) from 16 shape categories, each annotated with 2 to 6 parts and there are 50 different parts in total. 

so, should i add a vector of 16 dims which named label_weights ?
Awaiting for your reply .Thank you very much

**Comment by limin1130** [comment]
an other problem . After add the label_weights, there is a problem says that 

> PointCNN/PointCNN-master/sampling/tf_sampling_so.so: cannot open shared object file: No such file or directory
then  I run the `tf_sampling_compile.sh` ,it says 

> tf_sampling.cpp:6:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
compilation terminated.
Could you tell me the possible reason for this error

**Comment by MingChaoSun** [comment]
For the label_weights problem, in order to easily adjust the weight of different classes during the training, we add the label_weight parameter in the configuration file, you can add a list named label_weights like s3dis_x8_2048_k16_fps.py to fix this problem.

For the second problem, we compile it in TF1.4. Could you please travel to tensorflow/core/framework and check if the op.h there?

**Comment by MingChaoSun** [comment]
For the label_weights problem, in order to easily adjust the weight of different classes during the training, we add the label_weight parameter in the configuration file, you can add a list named label_weights like s3dis_x8_2048_k16_fps.py to fix this problem.

For the second problem, we compile it in Python3 and TF1.4. Could you please travel to tensorflow/core/framework and check wheter the op.h is in there?

**Comment by MingChaoSun** [comment]
For the label_weights problem, in order to easily adjust the weight of different classes during the training, we add the label_weight parameter in the config file. Now we have updated all config file.

For the second problem, we compile it in Python3 and TF1.4, and we didn't compile it in other versions.

**Comment by limin1130** [comment]
thanks you. The second problem does because the address of tensorflow. For the first problem ，I confuse the dim of the list, like s3dis_x8_2048_k16_fps.py is a 13 dims list, for it has 13 classes. then for  shapenet_x8_2048_fps.py ,is it 16 dims?

**Comment by MingChaoSun** [comment]
The label weights is for the segmentation parts, so for shapenet, it should be 50 dims (same as num_parts).

**Comment by limin1130** [comment]
got it. Thankyou very much.发自我的华为手机-------- 原始邮件 --------主题：Re: [yangyanli/PointCNN] train_val_shapenet.sh shapenet_x8_2048_fps error (#6)发件人：MingChaoSun 收件人：yangyanli/PointCNN 抄送：limin1130 ,Author The label weights is for the segmentation parts, so for shapenet, it should be 50 dims (same as num_parts).

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yangyanli/PointCNN","title":"yangyanli/PointCNN","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yangyanli/PointCNN"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MingChaoSun in #6: The label weights is for the segmentation parts, so for shapenet, it should be 50 dims (same as num_parts).\r\n"}],"action":{"name":"View Issue","url":"https://github.com/yangyanli/PointCNN/issues/6#issuecomment-364056109"}}}
