### ISSUE TITLE
Unterstanding the X-Conv Operator

### ISSUE THREAD

**Issue by romanskie** [yangyanli/PointCNN#73]
Hey Guys, 

I got some question regarding to the X-Conv Operator. I have some hard issues to unerstand it correctly.
Here is my interpretation so far:

1. First you learn a X-transformation matrix from representative set of points. The representative points are sampled from the original point set.

2. You build n local regions around every representative point with k neighbors.

3. You aggregate a feature from each local region to create a feature-map F* that includes all the features from n local regions.

4. You weight and permute the whole feature map F* with the learnt X-transformation to bring it in some canonical order => output is a ordered feature-map Fx

5. Finally, typical convolution between K and Fx.

I think I did not get that right. Could you please explain me the meaning of K in the typical convolution part. I don't understand as well if you are building a feature-map per local region, order it with the X-transformation and then convolve it. Or, if you aggregate a big feature-map from all the extracted local region features, order it with X-transformation and convolve that.
Do you learn the X-Transformation from the representative set of points or the "original" points?

Thank you in advance!

BG Roman

**Comment by godspeed1989** [comment]
I am not the author.
But here is my understanding:

1) I think X-conv learn X-transformation from local region.
2) X-Transformation is applied recursively on the "original" points. So it is learnt from both 'the representative set of points' and 'the original points'

**Comment by yangyanli** [comment]
Hi @romanskie ,

@godspeed1989 is right on 1: X-transformations are learnt from local regions,one from the neighborhood of each representative point. As for 2, since the whole network is hierarchical, similar to that in typical image CNNs, the representative points of one layer can be the "original" points of next layer, and the learnt transformation is applied on the *features* of the "original" points.

The X-transformation is learnt from the *local region* point coordinates, and applied on the *features* of the *local region* points, while in PointNet, the transformation is learnt from the entire input, and applied on the points (or the features) of the entire input. Also, the motivation is different: the most central goal of PointCNN is to enable CNN in point cloud, by transforming features associated with points into canonical space (permuting and weighting), while in PointNet, the goal is more about overall point order invariance,  and there is no convolution -- the thing that was shown to be the key in image CNNs.
